/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const UsersLazyImport = createFileRoute('/users')()
const CreateUserLazyImport = createFileRoute('/create-user')()
const IndexLazyImport = createFileRoute('/')()
const ProfileUserIdLazyImport = createFileRoute('/profile/$userId')()

// Create/Update Routes

const UsersLazyRoute = UsersLazyImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users.lazy').then((d) => d.Route))

const CreateUserLazyRoute = CreateUserLazyImport.update({
  id: '/create-user',
  path: '/create-user',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/create-user.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProfileUserIdLazyRoute = ProfileUserIdLazyImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/profile/$userId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/create-user': {
      id: '/create-user'
      path: '/create-user'
      fullPath: '/create-user'
      preLoaderRoute: typeof CreateUserLazyImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/create-user': typeof CreateUserLazyRoute
  '/users': typeof UsersLazyRoute
  '/profile/$userId': typeof ProfileUserIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/create-user': typeof CreateUserLazyRoute
  '/users': typeof UsersLazyRoute
  '/profile/$userId': typeof ProfileUserIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/create-user': typeof CreateUserLazyRoute
  '/users': typeof UsersLazyRoute
  '/profile/$userId': typeof ProfileUserIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-user' | '/users' | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-user' | '/users' | '/profile/$userId'
  id: '__root__' | '/' | '/create-user' | '/users' | '/profile/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CreateUserLazyRoute: typeof CreateUserLazyRoute
  UsersLazyRoute: typeof UsersLazyRoute
  ProfileUserIdLazyRoute: typeof ProfileUserIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CreateUserLazyRoute: CreateUserLazyRoute,
  UsersLazyRoute: UsersLazyRoute,
  ProfileUserIdLazyRoute: ProfileUserIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-user",
        "/users",
        "/profile/$userId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/create-user": {
      "filePath": "create-user.lazy.tsx"
    },
    "/users": {
      "filePath": "users.lazy.tsx"
    },
    "/profile/$userId": {
      "filePath": "profile/$userId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
